accounts/urls.py
from django.urls import path
from accounts.views import *
app_name = 'signup'
urlpatterns = [
     path('signup',signup_view, name='signup'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from blog.views import *
app_name = 'blog'
urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', blog_single_view, name='single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('author/<str:author_username>', blog_view, name='author'),
    path('search/', search_view, name='search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap
from website.sitemaps import StaticViewSitemap
sitemaps = {
    'static': StaticViewSitemap,
    'blog' : BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', include('accounts.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404='website.views.handler_not_found'

website/urls.py
from django.contrib import admin
from django.urls import path
from website.views import *
app_name = 'website'
urlpatterns = [
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('newsletter', newsletter_view, name='newsletter'),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from distutils.command.upload import upload
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Post(models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category)
    content_view = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_at = models.DateTimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} - {}" .format(self.title, self.id)

    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid': self.id})

website/models.py
import email
from django.db import models

# Create your models here.
class Contact(models.Model):
     name = models.CharField(max_length=255)
     email = models.EmailField()
     subject = models.CharField(max_length=255,blank=True)
     message = models.TextField()
     created_at = models.DateTimeField(auto_now_add=True)
     update_at = models.DateTimeField(auto_now=True)
     class Meta:
          ordering = ['created_at']
     def __str__(self):
          return self.name

class NewsLetter(models.Model):
     email = models.EmailField()

     def __str__(self):
          return self.email

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=255)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

class LoginForm(AuthenticationForm):
    email = forms.EmailField(max_length=254)
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

website/forms.py
from django import forms
from website.models import Contact, NewsLetter
from captcha.fields import CaptchaField

class ContactForm(forms.ModelForm):
    
    class Meta:
        model = Contact
        fields = '__all__'
class NewsLetterForm(forms.ModelForm):

    class Meta:
        model = NewsLetter
        fields = '__all__'

accounts/views.py
import email
from multiprocessing import context
from urllib import request
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from accounts.forms import SignUpForm, LoginForm
# Create your views here.


def signup_view(request):
    if not request.user.is_authenticated:
        
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('/')
        
        form = SignUpForm()
        context = {'form': form}
        return render(request, 'signup/signup.html', context)
    else:
        return redirect('/')

blog/views.py
from atexit import register
import datetime
from pickle import NONE
from django.shortcuts import render, get_object_or_404
from blog.models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def blog_view(response, cat_name=None, author_username=None, **kwargs):
    posts = Post.objects.filter(status=1,published_at__lte=datetime.datetime.now()).order_by('-created_at')
    if author_username:
        posts = posts.filter(author__username=author_username)
    if cat_name:
        posts = posts.filter(category__name=cat_name)

    if kwargs.get('tag_name') != None:
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])
    posts = Paginator(posts, 3)
    try:
        page_num = response.GET.get('page')
        posts = posts.get_page(page_num)
    except EmptyPage:
        posts = posts.get_page(1)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    context = {'posts': posts}
    return render(response, 'blog/blog-home.html', context)


def blog_single_view(response, pid):
    posts = Post.objects.filter(status=1, published_at__lte=datetime.datetime.now()).order_by('-created_at')
    post = get_object_or_404(posts, pk=pid, status=1)
    post.content_view += 1
    post.save()
    nextpost = Post.objects.filter(id__gt=post.pk).order_by('pk').first()
    prevpost = Post.objects.filter(id__lt=post.pk).order_by('pk').last()
    context = {'post': post, 'nextpost': nextpost, 'prevpost': prevpost}

    return render(response, 'blog/blog-single.html', context)


def search_view(response):
    posts = Post.objects.filter(status=1)
    if response.method == 'GET':
        if s := response.GET.get('s'):
            posts = posts.filter(content__contains=s)
    context = {'posts': posts}
    return render(response, 'blog/blog-home.html', context)

website/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from website.forms import ContactForm, NewsLetterForm
from django.contrib import messages

def index_view(response):
    return render(response, 'website/index.html')


def about_view(response):
    return render(response, 'website/about.html')


def newsletter_view(response):
    if response.method == 'POST':
        form = NewsLetterForm(response.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')

def contact_view(response):
    if response.method == 'POST':
        form = ContactForm(response.POST)
        if form.is_valid():
            fs= form.save(commit=False)
            fs.name= "uknown"
            fs.save()
            messages.add_message(response, messages.SUCCESS,'successfully!')
        else:
            messages.add_message(response, messages.ERROR,'your ticket didnt submited!')
    form = ContactForm()
    return render(response, 'website/contact.html')

def handler_not_found(request, exception):
    return render(request, 'not-found.html')

templates/base.html
{% load static %}
{% load blog_tags %}
{% load compress %}
<!DOCTYPE HTML>
<html lang="en-gb" class="no-js">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Gloss</title>
    <meta name="description" content="">
    <meta name="author" content="Themesrefinery">

    {% compress css inline %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style-animate.css' %}" />
    <link href="{% static 'font/css/font-awesome.min.css" rel="stylesheet' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slider.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
    {% endcompress %}
</head>


<body>
    <!--Top Header-->
    <header class="header">
        <div class="container">
            <nav class="navbar navbar-inverse" role="navigation">
                <div class="navbar-header">
                    <button type="button" id="nav-toggle" class="navbar-toggle" data-toggle="collapse"
                        data-target="#main-nav"> <span class="sr-only">Toggle navigation</span> <span
                            class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                    </button>
                    {% if request.user.is_authenticated %}
                    
                    <a href="#" class="navbar-brand scroll-top logo animated bounceInLeft rollIn"><b><i
                        class="fa fa-html5">logged in as {{request.user.username}}!</i></b></a>
                    <a href="{% url 'logout' %}" class="navbar-brand scroll-top logo animated bounceInLeft rollIn"><b><i
                        class="fa fa-html5">Logout</i></b></a>
                    {% else %}
                    <a href="{% url 'login' %}" class="navbar-brand scroll-top logo animated bounceInLeft rollIn"><b><i
                                class="fa fa-html5">Login</i></b></a>
                    <a href="{% url 'signup:signup' %}"
                        class="navbar-brand scroll-top logo animated bounceInLeft rollIn"><b><i
                                class="fa fa-html5">Signin</i></b></a>
                    {% endif %}


                </div>

                <div id="main-nav" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav" id="mainNav">
                        <li><a href="{% url 'website:index' %}">Home</a></li>
                        <li><a href="{% url 'website:about' %}">About me</a></li>
                        <li><a href="{% url 'blog:index' %}">Blog</a></li>
                        <li><a href="{% url 'website:contact' %}">Contact</a></li>
                        
                    </ul>
                </div>

            </nav>
        </div>
    </header>
    {% if messages %}
          {% for message in messages %}
          <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %} m-2" id="msg" role="alert">{{ message|safe }}</div>
          {% endfor %}
          {% endif %}
    <!--Top Header End-->
    {% block content %}

    {% endblock %}
    

    <!--Footer Start-->
    <footer>
        <div class="row">
            
            {% latestpost %}
        </div>
        
        <div class="col-lg-12 top2 bottom2">
            
            <div class="text-center">Design By <a href="#"><i
                        class="fa  fa-file-code">Arash Darabi</i></a></div>
        </div>
    </footer>
    <!--Footer End-->
    </div>
    <!--Main Body End-->
    {% compress js inline %}
    <script src="{% static 'js/jquery-1.11.1.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jssor.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jssor.slider.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/slider.js' %}" type="text/javascript"></script>
    {% endcompress %}
    <script>
        setTimeout(function () {
             if ($('#msg').length > 0) {
                  $('#msg').remove();
             }
        }, 2000);
   </script>
</body>

</html>

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load blog_tags %}
<!--Breadcrumbs-->
<div class="col-lg-12 top2">
	<div class="container">

		<ul class="breadcrumb">

			<li><a href="{% url 'website:about' %}">Home</a></li>

			<li class="active">Blog</li>

		</ul>

	</div>
</div>
<!--Breadcrumbs-->

<!--Blog Body-->

<div class="container">
	<div class="row">

		<div class="col-md-8">
			<div class="panel">
				<div class="panel-body">


					<!--/Blog Posts-->
					{% for post in posts %}
					<div class="row posts">
						<br>
						<div class="col-md-2 col-sm-3 text-center">
							<a class="story-img" href="{% url 'blog:single' pid=post.id %}"><img
									src="{{post.image.url}}" style="width:100px;height:100px"
									class="img-circle"></a>
						</div>
						<div class="col-md-10 col-sm-9">
							<h3 href="{% url 'blog:single' pid=post.id %}">{{post.title}}</h3>
							<div class="row">
								<div class="col-xs-9">
									<p>{{post.content|truncatewords:41|safe }}</p>
									<p class="lead" ><button class=" btn btn-default btn-hover"><a
											href="{% url 'blog:single' pid=post.id %}">Read
											More</a></button></p>
									{% for cat in post.category.all %}
									<p class="pull-right"><span class="label label-default"><a
												href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name }}</a></span>
										{% endfor %}
									<ul class="list-inline">
										<li><a
												href="{% url 'blog:author' author_username=post.author.username %}"><i
													class="fa fa-comment"></i>{{post.author.get_full_name}}</a>
										</li>
										<li><a href="#">{{post.published_at|date:"d M Y"}}</a></li>

										<li><a href="#"><i class="fa fa-share"></i>{{post.content_view}}
												Views</a></li>
									</ul>
								</div>
								<div class="col-xs-3"></div>
							</div>
							<br><br>
						</div>
					</div>
					{% endfor %}
					<!--/Blog Posts-->





				</div>
				<!--Pagniation-->
				<div class="container">
					<div class="row table">
						<div class="text-center col-lg-8">
							<a class="btn btn-default btn-hover btn-block toggle-pagination"><i
									class="glyphicon glyphicon-plus"></i> Toggle Pagination</a>
							<ul class="pagination pagination-responsive pagination-lg">

								{% if posts.has_previous %}
								<li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
								{% endif %}
								{% for i in posts.paginator.page_range %}
								{% if posts.number == i %}
								<li><a href="?page={{i}}">{{i}}</a></li>
								{% else %}
								<li><a href="?page={{i}}">{{i}}</a></li>
								{% endif %}
								{% endfor %}
								{% if posts.has_next %}
								<li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
								{% endif %}
							</ul>
						</div>
					</div>
				</div>
				<!--Pagniation End-->
			</div>



		</div>
		<!--/col-8-->
		<!--Sidebar Start-->
		<div class="col-md-4">

			<!-- Blog Search Well -->
			{% include 'blog/blog-search.html'%}

			{% postcategories %}
			{% include 'blog/side-widget.html'%}
			<!-- Blog Categories Well -->


			<!-- Side Widget Well -->


		</div>
		<!--Sidebar End-->
	</div>
	{% endblock %}

templates/blog/blog-newsletter.html
{% load static %}
<div class="col-lg-3  col-md-6 col-sm-6">
     <div class="single-footer-widget">
          <h6>Newsletter</h6>
          
          <div>
               <form action="{% url 'website:newsletter' %}" method="post"
                    class="subscription relative">
                    {% csrf_token %}
                    <div class="input-group d-flex flex-row">
                         <input name="email" placeholder="Email Address"
                              onfocus="this.placeholder = ''"
                              onblur="this.placeholder = 'Email Address '" required="" type="email">
                              <button type="submit"><i class=" btn btn-default btn-hover"></i></button>
                    </div>
                    <div class="mt-10 info"></div>
               </form>
          </div>
     </div>
</div>

templates/blog/blog-popular-post.html
{% load static %}
{% load humanize %}
<div class="col-lg-4">
     <h1>Recent Posts</h1>
     <ul class="list-unstyled">
          {% for post in posts %}
          <li><a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a></li>
          <p>{{post.published_at|naturaltime}}</p>
          {% endfor %}
     </ul>
</div>

templates/blog/blog-post-category.html
{% load static %}
<div class="well">
    <h4>Blog Categories</h4>
    <div class="row">

        <div class="col-lg-6">
            <ul class="list-unstyled">
                {% for name,count in categories.items %}
                <li><a href="{% url 'blog:category' cat_name=name%}" class="d-flex justify-content-between"><p>{{name}}   {{count}}</p></a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <!-- /.row -->
</div>

templates/blog/blog-search.html
{% load static %}
<div class="well">
     <h4>Blog Search</h4>
     <form class="search-form" action="{% url 'blog:search' %}" method="get">
        <input placeholder="Search Posts" name="s" type="text"
             onfocus="" this.placeholder = '' this.placeholder = 'Search Posts'>
        <button type="submit"><i class=" btn btn-default btn-hover"></i></button>
   </form>
     <!-- /.input-group -->
 </div>

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load blog_tags %}
<!--Breadcrumbs-->
<div class="col-lg-12 top2">
	<div class="container">

		<ul class="breadcrumb">

			<li><a href="{% url 'website:about' %}">Home</a></li>

			<li class="active">Post Title</li>

		</ul>
	</div>

</div>
<!--Breadcrumbs-->

<!--Main Body-->
<div class="container">
	<div class="row">
		<div class="col-lg-8">
			<div class="col-md-12">
				<h1>{{post.title}}</h1>
				<div class="entry-meta table">
					<span>
						Written by:
						<a
							href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a>
					</span>
					<span>{{post.published_at|date:"d M Y"}}</span>
					<span>{{post.content_view}} Views</span>
					<span>
						{% for tag in post.tags.all %}
						<li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></li>
						{% endfor %}
					</span>
				</div>
				<div>
					<img src="{{post.image.url}}" class="img-responsive" alt="fashion">
				</div>
				<div class="media">
					<p>{{post.content|safe}}</p>

				</div>

			</div>
			<div class="navigation-area">
				<div class="row">
					<div
						class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">

						<div class="detials">
							<p>Prev Post</p>
							{% if prevpost %}
							<a style="color:rgb(0, 0, 0);" href="{{ STATIC_URL }}/blog/{{prevpost.id}}">{{prevpost}}
							</a>
							{% endif %}
						</div>
					</div>
					<div
						class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">



						<div class="detials">
							<p>Next Post</p>
							{% if nextpost %}
							<a style="color:rgb(0, 0, 0);" href="{{ STATIC_URL }}/blog/{{nextpost.id}}">{{nextpost}}
							</a>
							{% endif %}
						</div>
					</div>
				</div>
			</div>

		</div>

		<!--Sidebar Start-->
		<div class="col-md-4 top3">



			<!-- Blog Search Well -->
			{% include 'blog/blog-search.html'%}

			{% postcategories %}
			{% include 'blog/side-widget.html'%}
			<!-- Blog Categories Well -->
			

			<!-- Side Widget Well -->




		</div>
		<!--Sidebar End-->
		
		<!--Comment-->
		<div class="container">
			<div class="row">
				<div class="col-md-8">
					<h2 class="page-header">Comments</h2>
					<section class="comment-list">

						<div id="disqus_thread"></div>
						<script>
							/**
							*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
							*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
							/*
							var disqus_config = function () {
							this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
							this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
							};
							*/
							(function () { // DON'T EDIT BELOW THIS LINE
								var d = document, s = d.createElement('script');
								s.src = 'https://127-0-0-1-8000-zr7ug5cati.disqus.com/embed.js';
								s.setAttribute('data-timestamp', +new Date());
								(d.head || d.body).appendChild(s);
							})();
						</script>
						<noscript>Please enable JavaScript to view the <a
								href="https://disqus.com/?ref_noscript">comments powered by
								Disqus.</a></noscript>
					</section>
				</div>
			</div>
		</div>
		<!--Comment End-->
	</div>


	{% endblock %}

templates/blog/blog-tag-cloud.html
{% load static %}
<div class="single-sidebar-widget tag-cloud-widget">
     <h4 class="tagcloud-title">Tag Clouds</h4>
     <ul>
          {% for tag in post.tags.all %}
          <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></li>
          {% endfor %}
     </ul>
</div>

templates/blog/side-widget.html
{% load static %}
{% include "blog/blog-newsletter.html" %}

templates/not-found.html
{% load static %}
<html>

<head>
     <meta charset="utf-8">

     <title>gloss</title>
</head>

<body>

     <h1 align="center">
          !404! به زودی در دسترس خواهد بود</br>
          <a href="{% url 'website:index' %}">صفحه اصلی</a>
     </h1>

    

</body>

</html>

templates/signup/signup.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    

    <title>Signup</title>

    
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/signin.css' %}">
  </head>

  <body class="text-center">
    <form class="form-signin" method="post" action="{% url 'signup:signup' %}">
     {% csrf_token %}
      
      <h1 class="h3 mb-3 font-weight-normal">Registration Form</h1>
      <label for="inputEmail" class="sr-only">username</label>
      <input type="text" name="username" class="form-control" placeholder="username" required autofocus>
      <input type="email" name="email" class="form-control" placeholder="email" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" name="password1" class="form-control" placeholder="password" requiredPassword" required>
      <input type="password" name="password2" class="form-control" placeholder="confirm password" requiredPassword" required>
      <div class="checkbox mb-3">
        <label>
          
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      
    </form>
  </body>
</html>

templates/website/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load blog_tags %}
<!--Top Header End-->

    <!--Breadcrumbs-->
    <div class="col-lg-12 top2">
	<div class="container">
 
	    <ul class="breadcrumb">
	
		   <li><a href="{% url 'website:about' %}">Home</a></li>
	
		   <li class="active">About</li>
	
	    </ul>
	
	</div>
	</div>
 <!--Breadcrumbs-->
 
<!--Main Body-->
<div class="container">
<div class="row">
    <div class="col-lg-8 top3">
    
	    <p>I love html. CSS. It is simple to learn, personalize, and great for fast development of responsive sites. Whether you are a seasoned developer/designer or someone learning the basics of web design and development, html. CSS is great way to start with all of its out-of-the-box parts.

Building sites for several years has given us an appreciation for the hard work and time it takes to generate pretty work. They also understand the worth of using themes & templates to kickstart the design & development process.

html. CSS has come a long way and they desired to generate an amazing marketplace for html. CSS lovers like ourselves.For Further Free Templates signup our newsletter</p> 
	  <hr>
	  <h1 class="top1">Our Mission</h1>
	<p>To be the #1 community for free supplier of html. CSS themes and templates.</p>
    </div>
 <!--Sidebar Start-->
 <div class="col-md-4 top3">

		   <!-- Blog Search Well -->


			<!-- Blog Search Well -->
			{% include 'blog/blog-search.html'%}
			
			{% postcategories %}
			{% include 'blog/side-widget.html'%}
			<!-- Blog Categories Well -->
			

			<!-- Side Widget Well -->
			



	    </div>
  <!--Sidebar End-->
</div>

{% endblock %}

templates/website/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load blog_tags %}
    <!--Breadcrumbs-->
    <div class="col-lg-12 top2">
	<div class="container">
 
	<ul class="breadcrumb">
 
	    <li><a href="{% url 'website:about' %}">Home</a></li>
 
	    <li class="active">Contact</li>
 
	</ul>
 
 </div>
 </div>
 <!--Breadcrumbs-->
 
<!--Main Body-->
<div class="container">
<div class="row">
    <div class="col-lg-8">
	    <form class="form-horizontal" role="form" action="{% url 'website:contact' %}"  method="post" >
		{% csrf_token %}
		
		   <div class="form-group">
			  <label for="name" class="col-sm-2 control-label">Name</label>
			  <div class="col-sm-10">
				<input name="name" placeholder="Enter your name" this.placeholder = ''
				 this.placeholder = 'Enter your name'
				class="common-input mb-20 form-control" required="" type="text">
			  </div>
		   </div>
		   <div class="form-group">
			  <label for="email" class="col-sm-2 control-label">Email</label>
			  <div class="col-sm-10">
				<input name="email" placeholder="Enter email address"
				pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$"
				this.placeholder = ''
				this.placeholder = 'Enter email address'
				class="common-input mb-20 form-control" required="" type="email">

			  </div>
		   </div>
		   <div class="form-group">
			<label for="subject" class="col-sm-2 control-label">subject</label>
			<div class="col-sm-10">
				<input name="subject" placeholder="Enter subject" this.placeholder = ''
				this.placeholder = 'Enter subject'
				class="common-input mb-20 form-control" type="text">
			</div>
		 </div>
		   <div class="form-group">
			  <label for="message" class="col-sm-2 control-label">Message</label>
			  <div class="col-sm-10">
				<textarea class="common-textarea form-control" name="message"
				placeholder="Enter Messege"  this.placeholder = ''
			     this.placeholder = 'Enter Messege' required=""></textarea>
			  </div>
		   </div>
		
		   <div class="col-lg-12">
			
			<div class="alert-msg" style="text-align: center;"></div>
			<button type="submit" class="genric-btn primary" style="float: right;">Send Message</button>
		</div>
		   
	    </form> 
    </div>
  
 <!--Sidebar Start-->
 <div class="col-md-4 top3">

	<!-- Blog Search Well -->


	  <!-- Blog Search Well -->
	  {% include 'blog/blog-search.html'%}
	  
	  {% postcategories %}
	  {% include 'blog/side-widget.html'%}
	  <!-- Blog Categories Well -->
	  

	  <!-- Side Widget Well -->
	  



 </div>
  <!--Sidebar End-->
</div>

{% endblock %}

templates/website/website-search.html
{% load static %}
<div class="well">
     <h4>Blog Search</h4>
     <div class="input-group">
         <input type="text" class="form-control">
         <span class="input-group-btn">
             <button class="btn btn-default" type="button">
                 <i class="fa fa-search"></i>
         </button>
         </span>
     </div>
     <!-- /.input-group -->
 </div>